contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #ifunmap channel"
    url: https://nfcore.slack.com/channels/ifunmap
    about: Discussion about the nf-core/ifunmap pipeline
